name: Upgrade a package and create a pull request in another repo

on:
  workflow_dispatch:
    inputs:
      targetRepository:
        description: 'Name of the target repository where the pull request will be created'
        required: true

env:
    NEW_PACKAGE_NAME: 'lodash'
    TARGET_REPOSITORY: ${{ github.event.inputs.targetRepository }}

jobs:
  install-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Display Package Version
        id: display-version
        run: echo "PACKAGE_VERSION=$(npm show ${{ env.NEW_PACKAGE_NAME }} version)" >> "$GITHUB_ENV"

      # - name: Create New Branch
      #   run: git checkout -b update-lodash-to-"$PACKAGE_VERSION"

      - name: Update Package
        run: npm install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "joanna.derks@gmail.com"
          git config --global user.name "asia-t"
          git status

      # git add package.json package-lock.json
      # git commit -m 'Update ${{ env.NEW_PACKAGE_NAME }}@ to version "$PACKAGE_VERSION"'
      # git push origin update-lodash-to-"$PACKAGE_VERSION"

      # - name: Create Pull Request
      #   run: gh pr create --base main --head update-lodash-to-"$PACKAGE_VERSION" --title 'Install ${{ env.NEW_PACKAGE_NAME }}@"$PACKAGE_VERSION"' --body 'Install ${{ env.NEW_PACKAGE_NAME }}@"$PACKAGE_VERSION"'  --repo ${{ env.TARGET_REPOSITORY }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_ANOTHER_REPO }}
          commit-message: "Install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}"
          title: "Install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}"
          body: "Install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}"
          branch: update-lodash-to-${{ env.PACKAGE_VERSION }}

  # create-pull-request:
  #   needs: install-package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout target repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: ${{ env.TARGET_REPOSITORY }}
      
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v5
     
