name: Upgrade a package and create a pull request in another repo

on:
  workflow_dispatch:
    inputs:
      targetRepository:
        description: 'Name of the target repository where the pull request will be created'
        required: true

env:
    NEW_PACKAGE_NAME: 'lodash'
    TARGET_REPOSITORY: ${{ github.event.inputs.targetRepository }}

jobs:
  install-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPOSITORY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Display Package Version
        id: display-version
        run: echo "PACKAGE_VERSION=$(npm show ${{ env.NEW_PACKAGE_NAME }} version)" >> "$GITHUB_ENV"

      - name: Create New Branch
        run: git checkout -b update-lodash-to-"$PACKAGE_VERSION"

      - name: Update Package
        run: npm install ${{ env.NEW_PACKAGE_NAME }}@"$PACKAGE_VERSION"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "joanna.derks@gmail.com"
          git config --global user.name "asia-t"
          git status

#            git add package.json package-lock.json
#            git commit -m "Update ${{ env.NEW_PACKAGE_NAME }}@ to version ${{ env.PACKAGE_VERSION }}"
#            git push origin main

#  create-pull-request:
#    needs: install-package
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#
#      - name: Create Pull Request
#        run: |
#          git checkout -b install-package-branch
#          git push origin install-package-branch
#          gh pr create --base main --head install-package-branch --title "Install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}" --body "Install ${{ env.NEW_PACKAGE_NAME }}@${{ env.PACKAGE_VERSION }}"  --repo ${{ env.TARGET_REPOSITORY }}
